files:
- generatedChecksum: B9388144EA8C18C396F2DB6CC40DCB4D
  logicalPath: config\sam_rh71_ek
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9388144EA8C18C396F2DB6CC40DCB4D
- generatedChecksum: 1FD72247FC7074365167E63523BD425F
  logicalPath: config\sam_rh71_ek
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FD72247FC7074365167E63523BD425F
- generatedChecksum: 5A333C013DEA1E5945E675BA7C483381
  logicalPath: config\sam_rh71_ek
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5A333C013DEA1E5945E675BA7C483381
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_rh71_ek
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: B342F5D1F6C366397DCF479955D535E2
  logicalPath: config\sam_rh71_ek\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B342F5D1F6C366397DCF479955D535E2
- generatedChecksum: 31B2FB9FDF0A9B0247BFD5B67DCD8CDB
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\usart
  name: plib_flexcom1_usart.c
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31B2FB9FDF0A9B0247BFD5B67DCD8CDB
- generatedChecksum: 6B975AC09F679B0138CEFDDECF3E6155
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\spi
  name: plib_flexcom2_spi.c
  physicalPath: peripheral\flexcom\spi
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6B975AC09F679B0138CEFDDECF3E6155
- generatedChecksum: 1C4F8D660470F4E9E5932265A2C3C99C
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\usart
  name: plib_flexcom5_usart.c
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8AA3A7280244C8B431D18A4A062455F
- generatedChecksum: A24E70DE473CAD80AF95B829F2F477EF
  logicalPath: config\sam_rh71_ek\peripheral\matrix
  name: plib_matrix.c
  physicalPath: peripheral\matrix
  security: NON_SECURE
  type: SOURCE
  userChecksum: A24E70DE473CAD80AF95B829F2F477EF
- generatedChecksum: 41385C452DC5A07F6A7D6CD0D0BF6BBF
  logicalPath: config\sam_rh71_ek\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 41385C452DC5A07F6A7D6CD0D0BF6BBF
- generatedChecksum: 1BBC3BFC69B2B87C25CC20B82FCDF90B
  logicalPath: config\sam_rh71_ek\peripheral\pio
  name: plib_pio.c
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1BBC3BFC69B2B87C25CC20B82FCDF90B
- generatedChecksum: D277D0168654CD6AA8BF1AA7312E5865
  logicalPath: config\sam_rh71_ek\peripheral\systick
  name: plib_systick.c
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: SOURCE
  userChecksum: D277D0168654CD6AA8BF1AA7312E5865
- generatedChecksum: 3641D9477C8B457EC80AC1DF106431C2
  logicalPath: config\sam_rh71_ek
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3641D9477C8B457EC80AC1DF106431C2
- generatedChecksum: 1475F79BB40406FAFC7794791D39D792
  logicalPath: config\sam_rh71_ek\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1475F79BB40406FAFC7794791D39D792
- generatedChecksum: DDC3118D028649027D05C53A2F8360A2
  logicalPath: packs\ATSAMRH71F20C_DFP
  name: atsamrh71f20c.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: DDC3118D028649027D05C53A2F8360A2
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 2318FA522FCB163DFF6ED16346104B32
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: chipid.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2318FA522FCB163DFF6ED16346104B32
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
- generatedChecksum: 6BCE8A33EC1A5C48B23EB2A97E4C085C
  logicalPath: config\sam_rh71_ek
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6BCE8A33EC1A5C48B23EB2A97E4C085C
- generatedChecksum: 7AF18B894A79CC9B76F29D14AB8D05E9
  logicalPath: config\sam_rh71_ek
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7AF18B894A79CC9B76F29D14AB8D05E9
- generatedChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
  logicalPath: config\sam_rh71_ek
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
- generatedChecksum: E5105F93C4537C4F74A48F2E18C7E675
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: flexcom.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E5105F93C4537C4F74A48F2E18C7E675
- generatedChecksum: CE6CB3A044D73FFD628BBCB8C14B0248
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: flexramecc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CE6CB3A044D73FFD628BBCB8C14B0248
- generatedChecksum: E967DEA1B5E1013A55FE40E2D14BC0FD
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: gmac.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E967DEA1B5E1013A55FE40E2D14BC0FD
- generatedChecksum: 884F1B9EAAD5F03E6D0014324A4DDA2D
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: hefc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 884F1B9EAAD5F03E6D0014324A4DDA2D
- generatedChecksum: 33F5152574282A03BE092FA2D6ED5D87
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: hemc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 33F5152574282A03BE092FA2D6ED5D87
- generatedChecksum: 00988CBE06C333AF4546867190197E09
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: hsdramc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 00988CBE06C333AF4546867190197E09
- generatedChecksum: E4E9BBC6BE24F3CAEB285602D310E0D8
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: hsmc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E4E9BBC6BE24F3CAEB285602D310E0D8
- generatedChecksum: B57CD365D0030670CCA10C74D1AEA19E
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: icm.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B57CD365D0030670CCA10C74D1AEA19E
- generatedChecksum: FDE59CBB40F78C91BFE48384DFD881C0
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: ip1553.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FDE59CBB40F78C91BFE48384DFD881C0
- generatedChecksum: 4FBBBD06D43B387768166BFA289F323D
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: matrix.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4FBBBD06D43B387768166BFA289F323D
- generatedChecksum: 47B1A8B691843519F6982CA571BDE138
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: mcan.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 47B1A8B691843519F6982CA571BDE138
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: EB28A0BD2F4E34328B6101E7A924B95D
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: nmic.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EB28A0BD2F4E34328B6101E7A924B95D
- generatedChecksum: 6A05B0C56B877A4EE8B7F3D8AED87A5D
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: pio.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A05B0C56B877A4EE8B7F3D8AED87A5D
- generatedChecksum: 4A691040029E5ACD565BBAFC92FDDD7C
  logicalPath: config\sam_rh71_ek\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A691040029E5ACD565BBAFC92FDDD7C
- generatedChecksum: A9B80FD75135DBB0B8FF3163BB2A7219
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\usart
  name: plib_flexcom1_usart.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: A9B80FD75135DBB0B8FF3163BB2A7219
- generatedChecksum: 2CAF2B9A7AB2650B390613FEAA14D9D4
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\spi
  name: plib_flexcom2_spi.h
  physicalPath: peripheral\flexcom\spi
  security: NON_SECURE
  type: HEADER
  userChecksum: 2CAF2B9A7AB2650B390613FEAA14D9D4
- generatedChecksum: 8A95BAE207DC48D81C41D02038EC3972
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\usart
  name: plib_flexcom5_usart.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8A95BAE207DC48D81C41D02038EC3972
- generatedChecksum: 538640EE94FC456DEF805CD43163424A
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\spi
  name: plib_flexcom_spi_local.h
  physicalPath: peripheral\flexcom\spi
  security: NON_SECURE
  type: HEADER
  userChecksum: 538640EE94FC456DEF805CD43163424A
- generatedChecksum: F35B34B1D7286D8A5AF72DCA9D3B1DE5
  logicalPath: config\sam_rh71_ek\peripheral\flexcom\usart
  name: plib_flexcom_usart_local.h
  physicalPath: peripheral\flexcom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: F35B34B1D7286D8A5AF72DCA9D3B1DE5
- generatedChecksum: 9AFE036A32046351142FE93255A334B6
  logicalPath: config\sam_rh71_ek\peripheral\matrix
  name: plib_matrix.h
  physicalPath: peripheral\matrix
  security: NON_SECURE
  type: HEADER
  userChecksum: 9AFE036A32046351142FE93255A334B6
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_rh71_ek\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: FD10979115F0F6A4F191F94AFE4426A6
  logicalPath: config\sam_rh71_ek\peripheral\pio
  name: plib_pio.h
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: FD10979115F0F6A4F191F94AFE4426A6
- generatedChecksum: 6A645A71260B2ED5F22B51506F52D9B8
  logicalPath: config\sam_rh71_ek\peripheral\systick
  name: plib_systick.h
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A645A71260B2ED5F22B51506F52D9B8
- generatedChecksum: 2889D424DD539F9C327EEC3119B497D3
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: pmc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2889D424DD539F9C327EEC3119B497D3
- generatedChecksum: 5FF94AEAAF5BA6BD5168112CA2CA8B73
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: pwm.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FF94AEAAF5BA6BD5168112CA2CA8B73
- generatedChecksum: 6AAD66A052F5E21B736270357B821D1F
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: qspi.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6AAD66A052F5E21B736270357B821D1F
- generatedChecksum: DA69F0CBA539C9FC9B62D6B955492BAA
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DA69F0CBA539C9FC9B62D6B955492BAA
- generatedChecksum: 21447CA43D31A56670539F4791D114CB
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 21447CA43D31A56670539F4791D114CB
- generatedChecksum: 9F968E76ED48F4478D4D63D60DE9BD2F
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: rtt.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F968E76ED48F4478D4D63D60DE9BD2F
- generatedChecksum: 2F9C475F77A8F7A75AA96987E617221C
  logicalPath: packs\ATSAMRH71F20C_DFP\pio
  name: samrh71f20c.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 2F9C475F77A8F7A75AA96987E617221C
- generatedChecksum: FA65D5E5086352121676CE565C4A7523
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: sfr.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FA65D5E5086352121676CE565C4A7523
- generatedChecksum: FB11F35DA18EA948CA57B18FD04A4964
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: sha.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FB11F35DA18EA948CA57B18FD04A4964
- generatedChecksum: 7D1CE134190EE90C2A2CF869B63F8352
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: spw.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7D1CE134190EE90C2A2CF869B63F8352
- generatedChecksum: A6B5A6ABD7B2AAADB6B42F497B47E2C5
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A6B5A6ABD7B2AAADB6B42F497B47E2C5
- generatedChecksum: BEE26A1A1F1258AB815FF736E6D1970D
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BEE26A1A1F1258AB815FF736E6D1970D
- generatedChecksum: 0A447A17C87DC796170C90A3AE1C5432
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: tcmecc.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A447A17C87DC796170C90A3AE1C5432
- generatedChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
  logicalPath: config\sam_rh71_ek
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
- generatedChecksum: 175939D68F9F9163994858AF592F8C5B
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 175939D68F9F9163994858AF592F8C5B
- generatedChecksum: 68CB5DD1E632208308AC7502110CE925
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 68CB5DD1E632208308AC7502110CE925
- generatedChecksum: A83B9C5AEBFA4E897CDDF58C6B197585
  logicalPath: packs\ATSAMRH71F20C_DFP\component
  name: xdmac.h
  physicalPath: ..\..\packs\ATSAMRH71F20C_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A83B9C5AEBFA4E897CDDF58C6B197585
- generatedChecksum: CF5942FBBD008200475F39D9E5E535CC
  logicalPath: config\sam_rh71_ek
  name: ATSAMRH71F20C.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: CF5942FBBD008200475F39D9E5E535CC
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_rh71_ek;../src/packs/ATSAMRH71F20C_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_rh71_ek;../src/packs/ATSAMRH71F20C_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32Global
  delimiter: ''
  key: mdtcm
  security: NON_SECURE
  value: '0x40000'
- append: false
  category: C32Global
  delimiter: ''
  key: mitcm
  security: NON_SECURE
  value: '0x20000'
- append: false
  category: C32Global
  delimiter: ''
  key: mstacktcm
  security: NON_SECURE
  value: 'false'
sourcePaths: []
